server:
  port: 8080

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #是否将自己注册进eureka-server，默认true
    register-with-eureka: true
    #是否从注册中心（eureka-server）抓取已有的注册信息 默认true，集群必须设置为true，才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #单机版
      defaultZone: http://localhost:7001/eureka