server:
  port: 8084

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址（访问地址：http://192.168.68.132:8848/nacos）
        server-addr: 192.168.68.132:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址（访问地址：http://192.168.68.132:8080）
        dashboard: 192.168.68.132:8080
        #默认8719端口，若被占用会自动+1扫描，直到没有被占用
        port: 8719
      #sentinel利用nacos来实现持久化的相关配置，避免8084每次一重启，sentinel上的信息就消失了
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.68.132:8848
            dataId: nacos-order-consumer
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true