server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址（访问地址：http://192.168.68.132:8848/nacos）
        server-addr: 192.168.68.132:8848

#所有的Actuator端点都会对外暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'