server:
  port: 7002

# 单机版Eureka服务端
#eureka:
#  instance:
#    # eureka服务端的实例名字
#    hostname: localhost
#  client:
#    # false 表示不向注册中心注册自己
#    register-with-eureka: false
#    # false 表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
#    fetch-registry: false
#    service-url:
#      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 集群版Eureka服务端（C:\Windows\System32\drivers\etc\HOSTS 文件配置已修改）
eureka:
  instance:
    # eureka服务端的实例名字
    hostname: eureka7002.com
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 集群版 服务端之间相互注册 7002 ==》 7001
      defaultZone: http://eureka7001.com:7001/eureka/