server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    #gateway网关配置项（gateway的开启方式一：配置文件方式），示例含义相当于该网关挡在了 localhost:8001/payment/get/** 等等请求的前面
    #开启网关后，原URL可以访问，通过网关端口也可访问，如 localhost:9527/payment/get/**
    gateway:
      #正常工作中，provider肯定不止一个，所以provider的uri不能写死http://localhost:8001，需要动态创建
      #解决方案：开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          #写成动态路由形式，通过负载均衡调用provider
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
            #以下是常用的一些predicates配置，简单例举
            #在以下时间以后当前路由再生效
            - After=2022-12-09T10:59:34.102+08:00[Asia/Shanghai]
#            - Before=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
#            - Between=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] ,  2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
            #curl http://localhost:9527/payment/lb --cookie "username=wyuan"
#            - Cookie=username,wyuan   #Cookie=cookieName,正则表达式
            #请求头要有X-Request-Id属性并且值为整数的正则表达式 curl http://localhost:9527/payment/lb --cookie "username=wyuan" -H "X-Request-Id:11"
#            - Header=X-Request-Id, \d+
#            - Host=**.wy.com  # curl http://localhost:9527/payment/lb -H "Host:afae.wy.com"
            #指定GET请求才允许访问
#            - Method=GET

        - id: payment_routh2  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          #写成动态路由形式，通过负载均衡调用provider
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由

eureka:
  client:
    #是否将自己注册进eureka-server，默认true
    register-with-eureka: true
    #是否从注册中心（eureka-server）抓取已有的注册信息 默认true，集群必须设置为true，才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service