server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider

  cloud:
    nacos:
      discovery:
        #Nacos地址
        server-addr: 192.168.68.132:8848

#端口暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'